---
- name: Create container and upload a file
  azure_rm_storageblob:
    resource_group: "{{ azure_rg }}"
    storage_account_name: "{{ azure_storage_account_name}}"
    container: "{{ container_name }}"
    blob: migration/report.json
    src: files/report.json

- name: Download the file
  azure_rm_storageblob:
    resource_group: "{{ azure_rg }}"
    storage_account_name: "{{ azure_storage_account_name}}"
    container: "{{ container_name }}"
    blob: "{{ path_blob_name }}"
    dest: /tmp/report.json